### PR TITLE
Added header, nav, footer element placeholders

### PR DESCRIPTION
**Pull request by zwcrawford**
1. Check for spelling and formatting issues

### CODE REVIEW

**Comment by JordanRosas** [comment]
all good

**Comment by JordanRosas** [comment]
for future lets put first two steps to checking out updated branches ex

1. `git fetch --all BRANCHNAME`
1.`git checkout BRANCHNAME`
1.run http-server

**Review by JordanRosas — APPROVED** [review]
all good

**Review by gradyrobbins — APPROVED** [review]
👍 looks good man

**Pull request merged**
